spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 1082068479655-6r1pcv8tj0ai09fsr0p72f2n27kl421j.apps.googleusercontent.com
            client-secret: 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
            scope: profile,email
          kakao:
            client-id: 45a9364be0860449187fa915c9cd2e91
            client-name: Kakao
            redirect-uri: '{baseUrl}/{action}/oauth2/code/{registrationId}'
            # http://localhost:8080/login/oauth2/code/kakao
            scope: profile_nickname, profile_image
            authorization-grant-type: authorization_code
            client-authentication-method: client_secret_post
        provider:
          kakao:
            authorization_uri: https://kauth.kakao.com/oauth/authorize
            token_uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user_name_attribute: id